### ISSUE TITLE
Log file has NPE

### ISSUE THREAD

**Issue by bbockelm** [ncsa/oa4mp#106]
I currently have this logging configuration:

```
        <logging
                logFileName="/opt/scitokens-server/log/scitokens-server.log"
                logName="scitokens-server"
                logSize="100000"
                logFileCount="2"
                debug="trace"/>
```

in `server-config.xml` (note: I actually prefer logging to stdout; see #105).

However, when any interaction with an OAuth2 client is attempted, a NPE is thrown for each log message.  Here's the top of the exception, everything after the standard Tomcat frames:

```
Jun 12, 2023 8:16:34 PM edu.uiuc.ncsa.security.core.util.MyLoggingFacade error
SEVERE: could not load configuration
java.lang.NullPointerException
        at edu.uiuc.ncsa.security.core.util.LoggingConfigLoader.<init>(LoggingConfigLoader.java:84)
        at edu.uiuc.ncsa.security.core.util.LoggingConfigLoader.<init>(LoggingConfigLoader.java:112)
        at edu.uiuc.ncsa.oa4mp.delegation.common.servlet.DBConfigLoader.<init>(DBConfigLoader.java:30)
        at edu.uiuc.ncsa.myproxy.oa4mp.client.loader.AbstractClientLoader.<init>(AbstractClientLoader.java:46)
        at edu.uiuc.ncsa.oa4mp.oauth2.client.OA2ClientLoader.<init>(OA2ClientLoader.java:41)
        at edu.uiuc.ncsa.myproxy.oauth2.tools.OA2CommandLineClient.getLoader(OA2CommandLineClient.java:43)
        at edu.uiuc.ncsa.security.util.cli.ConfigurableCommandsImpl.getEnvironment(ConfigurableCommandsImpl.java:196)
        at edu.uiuc.ncsa.myproxy.oauth2.tools.OA2CLCCommands.<init>(OA2CLCCommands.java:108)
        at edu.uiuc.ncsa.oa2.servlet.ProxyUtils.getCLC(ProxyUtils.java:200)
        at edu.uiuc.ncsa.oa2.servlet.ProxyUtils.doRFC8628AT(ProxyUtils.java:246)
        at edu.uiuc.ncsa.oa2.servlet.OA2ATServlet.doRFC8628(OA2ATServlet.java:1675)
        at edu.uiuc.ncsa.oa2.servlet.OA2ATServlet.executeByGrant(OA2ATServlet.java:159)
        at edu.uiuc.ncsa.oa2.servlet.OA2ATServlet.doIt(OA2ATServlet.java:898)
        at edu.uiuc.ncsa.security.servlet.AbstractServlet.doPost(AbstractServlet.java:210)
        ...
```

Can we (a) have guidance on how to best configure the logging? and (b) improve the exception for whatever is causing the above error?

**Comment by jjg-123** [comment]
The error implies that it is not inside the right tag. Is it in something like this?
```

<config>
  <service>
    <logging ...
```

**Comment by bbockelm** [comment]
Yeah, it looks about right to me.  Here's the link to the config:

https://github.com/bbockelm/osdf-ospool-issuer/blob/main/scitokens-server/etc/server-config.xml#L20

**Comment by bbockelm** [comment]
As an update, the issue is actually coming from the proxy config:

https://github.com/scitokens/scitokens-oauth2-server/blob/master/scitokens-server/etc/proxy-config.xml.tmpl#L3

This can be reproduced rather trivially with the following container:

```
docker pull hub.opensciencegrid.org/sciauth/scitokens-oauth2-server:release-20230617-1557
```
